# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ApplicationIdentifier.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ApplicationIdentifier.proto',
  package='',
  serialized_pb=_b('\n\x1b\x41pplicationIdentifier.proto\"b\n\x15\x41pplicationIdentifier\x12\x0e\n\x06\x61uthor\x18\x01 \x02(\t\x12\x14\n\x0cpackage_name\x18\x02 \x02(\t\x12\x0f\n\x07version\x18\x03 \x02(\t\x12\x12\n\npublic_key\x18\x04 \x01(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_APPLICATIONIDENTIFIER = _descriptor.Descriptor(
  name='ApplicationIdentifier',
  full_name='ApplicationIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='author', full_name='ApplicationIdentifier.author', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='package_name', full_name='ApplicationIdentifier.package_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='ApplicationIdentifier.version', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='ApplicationIdentifier.public_key', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['ApplicationIdentifier'] = _APPLICATIONIDENTIFIER

ApplicationIdentifier = _reflection.GeneratedProtocolMessageType('ApplicationIdentifier', (_message.Message,), dict(
  DESCRIPTOR = _APPLICATIONIDENTIFIER,
  __module__ = 'ApplicationIdentifier_pb2'
  # @@protoc_insertion_point(class_scope:ApplicationIdentifier)
  ))
_sym_db.RegisterMessage(ApplicationIdentifier)


# @@protoc_insertion_point(module_scope)
