# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StationCommodities.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ApplicationIdentifier_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='StationCommodities.proto',
  package='',
  serialized_pb=_b('\n\x18StationCommodities.proto\x1a\x1b\x41pplicationIdentifier.proto\"\xe7\x04\n\x12StationCommodities\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12+\n\x0b\x61pplication\x18\x02 \x01(\x0b\x32\x16.ApplicationIdentifier\x12\x0e\n\x06system\x18\x03 \x02(\t\x12\x0f\n\x07station\x18\x04 \x02(\t\x12\x36\n\x0b\x63ommodities\x18\x05 \x03(\x0b\x32!.StationCommodities.CommodityInfo\x1a\xb7\x03\n\rCommodityInfo\x12\x46\n\toperation\x18\x01 \x01(\x0e\x32+.StationCommodities.CommodityInfo.Operation:\x06UPDATE\x12\x11\n\titem_name\x18\x02 \x02(\t\x12\x11\n\tbuy_price\x18\x03 \x01(\r\x12\x12\n\nsell_price\x18\x04 \x01(\r\x12\x15\n\rstation_stock\x18\x05 \x01(\r\x12\x16\n\x0estation_demand\x18\x06 \x01(\r\x12\x43\n\x0csupply_level\x18\x07 \x01(\x0e\x32-.StationCommodities.CommodityInfo.MarketLevel\x12\x43\n\x0c\x64\x65mand_level\x18\x08 \x01(\x0e\x32-.StationCommodities.CommodityInfo.MarketLevel\x12\x0f\n\x07illegal\x18\t \x01(\x08\",\n\tOperation\x12\n\n\x06UPDATE\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\n\n\x06REMOVE\x10\x02\",\n\x0bMarketLevel\x12\x07\n\x03LOW\x10\x00\x12\n\n\x06MEDIUM\x10\x01\x12\x08\n\x04HIGH\x10\x02')
  ,
  dependencies=[ApplicationIdentifier_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_STATIONCOMMODITIES_COMMODITYINFO_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='StationCommodities.CommodityInfo.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOVE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=583,
  serialized_end=627,
)
_sym_db.RegisterEnumDescriptor(_STATIONCOMMODITIES_COMMODITYINFO_OPERATION)

_STATIONCOMMODITIES_COMMODITYINFO_MARKETLEVEL = _descriptor.EnumDescriptor(
  name='MarketLevel',
  full_name='StationCommodities.CommodityInfo.MarketLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOW', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=629,
  serialized_end=673,
)
_sym_db.RegisterEnumDescriptor(_STATIONCOMMODITIES_COMMODITYINFO_MARKETLEVEL)


_STATIONCOMMODITIES_COMMODITYINFO = _descriptor.Descriptor(
  name='CommodityInfo',
  full_name='StationCommodities.CommodityInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='StationCommodities.CommodityInfo.operation', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_name', full_name='StationCommodities.CommodityInfo.item_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buy_price', full_name='StationCommodities.CommodityInfo.buy_price', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sell_price', full_name='StationCommodities.CommodityInfo.sell_price', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='station_stock', full_name='StationCommodities.CommodityInfo.station_stock', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='station_demand', full_name='StationCommodities.CommodityInfo.station_demand', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='supply_level', full_name='StationCommodities.CommodityInfo.supply_level', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='demand_level', full_name='StationCommodities.CommodityInfo.demand_level', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='illegal', full_name='StationCommodities.CommodityInfo.illegal', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATIONCOMMODITIES_COMMODITYINFO_OPERATION,
    _STATIONCOMMODITIES_COMMODITYINFO_MARKETLEVEL,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=673,
)

_STATIONCOMMODITIES = _descriptor.Descriptor(
  name='StationCommodities',
  full_name='StationCommodities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='StationCommodities.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='application', full_name='StationCommodities.application', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system', full_name='StationCommodities.system', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='station', full_name='StationCommodities.station', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commodities', full_name='StationCommodities.commodities', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_STATIONCOMMODITIES_COMMODITYINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=673,
)

_STATIONCOMMODITIES_COMMODITYINFO.fields_by_name['operation'].enum_type = _STATIONCOMMODITIES_COMMODITYINFO_OPERATION
_STATIONCOMMODITIES_COMMODITYINFO.fields_by_name['supply_level'].enum_type = _STATIONCOMMODITIES_COMMODITYINFO_MARKETLEVEL
_STATIONCOMMODITIES_COMMODITYINFO.fields_by_name['demand_level'].enum_type = _STATIONCOMMODITIES_COMMODITYINFO_MARKETLEVEL
_STATIONCOMMODITIES_COMMODITYINFO.containing_type = _STATIONCOMMODITIES
_STATIONCOMMODITIES_COMMODITYINFO_OPERATION.containing_type = _STATIONCOMMODITIES_COMMODITYINFO
_STATIONCOMMODITIES_COMMODITYINFO_MARKETLEVEL.containing_type = _STATIONCOMMODITIES_COMMODITYINFO
_STATIONCOMMODITIES.fields_by_name['application'].message_type = ApplicationIdentifier_pb2._APPLICATIONIDENTIFIER
_STATIONCOMMODITIES.fields_by_name['commodities'].message_type = _STATIONCOMMODITIES_COMMODITYINFO
DESCRIPTOR.message_types_by_name['StationCommodities'] = _STATIONCOMMODITIES

StationCommodities = _reflection.GeneratedProtocolMessageType('StationCommodities', (_message.Message,), dict(

  CommodityInfo = _reflection.GeneratedProtocolMessageType('CommodityInfo', (_message.Message,), dict(
    DESCRIPTOR = _STATIONCOMMODITIES_COMMODITYINFO,
    __module__ = 'StationCommodities_pb2'
    # @@protoc_insertion_point(class_scope:StationCommodities.CommodityInfo)
    ))
  ,
  DESCRIPTOR = _STATIONCOMMODITIES,
  __module__ = 'StationCommodities_pb2'
  # @@protoc_insertion_point(class_scope:StationCommodities)
  ))
_sym_db.RegisterMessage(StationCommodities)
_sym_db.RegisterMessage(StationCommodities.CommodityInfo)


# @@protoc_insertion_point(module_scope)
